### ISSUE TITLE
Add support for arbitrary arguments to firtool

### ISSUE THREAD

**Issue by oharboe** [sifive/chisel-circt#12]
I'd like to be able to pass arbitrary arguments through to the firtool.

Certainly during development of firtool and this module, I would expect there to be some arguments that aren't supported by ChiseStage annotations.

Some use-cases:

- Specify exactly how lowering is done, so that e.g. Yosys will work
- Adjust output style to match preferences more precisely

**Comment by seldridge** [comment]
I agree there should be some way to just let options through. I've been trying to do translation when possible, e.g., `-ll trace` is converted to `--print-ir-after-all` when it hits `firtool`. However, it is unrealistic to do this for things like firtool lowering options.

Great idea, @oharboe!

**Comment by seldridge** [comment]
There is now an annotation, `circt.stage.FirtoolOption(option: String)` which can be used to add an option to `firtool`. This annotation can be specified more than once to keep adding more options. An example of using this to produce case statements is shown in this test: https://github.com/sifive/chisel-circt/blob/main/src/test/scala/circtTests/stage/ChiselStageSpec.scala#L120
