### ISSUE TITLE
Lock firtool version to chisel-circt version

### ISSUE THREAD

**Issue by oharboe** [sifive/chisel-circt#21]
That way chisel-circt versions would be idempotent: check out a given version of chisel-circt and you get an exact version of the 
firtool....

As it is today, I get errors when I try chisel-circt 0.6.0 with the binary below because the ``-disable-infer-rw`` option doesn't exist in the binary below.

```
firtool: Unknown command line argument '-disable-infer-rw'.  Try: '../../../ascenium-firtool/bin/firtool --help'
firtool: Did you mean '--infer-rw'?
```

```
$ wget https://github.com/llvm/circt/releases/download/sifive%2F1%2F11%2F0/circt-bin-ubuntu-20.04.tar.gz
$ tar -xzvf circt-bin-ubuntu-20.04.tar.gz
[deleted]
$ bin/firtool --version
LLVM (http://llvm.org/):
  LLVM version 16.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver2

CIRCT unknown git version
```

**Comment by seldridge** [comment]
Unfortunately, I don't have a good solution for how to do this other than with textual information on the README.md or something as I don't know how to pull in a host dependency via Maven. (This is theoretically possible, but I haven't looked into how to do it.)

We did start publishing binaries of CIRCT on the releases page (https://github.com/llvm/circt/releases) to try to avoid the burden of compiling LLVM/CIRCT from source. The current version of chisel-circt (0.6.0) is known to be compatible with version 1.15.0+. (Using the latest, 1.19.0, would also work.)

I can start including the version of CIRCT that is known to work in the release notes as a bare minimum.

**Comment by seldridge** [comment]
I manually migrated this issue to: https://github.com/chipsalliance/chisel/issues/3053
